### ISSUE TITLE
Python conflict when also depending on esy-python

### ISSUE THREAD

**Issue by phated** [esy-packages/esy-ninja#2]
I think that esy-python just needs to be updated here, but I'm not exactly sure.

**Comment by ManasJayanth** [comment]
Whats the error message? Differing commit hashes?

The ideal solution would be making tagged releases IMO. Do you use this package regularly? I can figure something if so

**Comment by phated** [comment]
Yeah, it is a hash conflict because I think esy-python had some Windows fixes.

> Do you use this package regularly? I can figure something if so

I am trying to use esy-python, esy-cmake and esy-ninja to get https://github.com/grain-lang/binaryen.ml to build properly without using global installs (like we discussed in my esy PR), but I keep having resolution and path issues 😬

**Comment by ManasJayanth** [comment]
Done! Let me know if all is well 👍
